volumes:
  redis:
    driver: ${VOLUMES_DRIVER}

services:

### Redis ##############################################
  redis:
    build:
      context: ${REDIS_HOST_PATH}
      args:
        - REDIS_STACK_VERSION=${REDIS_STACK_VERSION}
    hostname: ${REDIS_HOSTNAME}
    container_name: ${REDIS_CONTAINER_NAME}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME}:/var/log/redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    environment:
      TZ: "${TZ}"
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --appendonly yes"
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "2>/dev/null", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10