volumes:
  meting-api-caddy:
    driver: ${VOLUMES_DRIVER}

services:

### CADDY ################################################
  meting-api-caddy:
    build:
      context: ${CADDY_HOST_PATH}
      args:
        - CADDY_VERSION=${CADDY_VERSION}
    hostname: ${CADDY_HOSTNAME}
    container_name: ${CADDY_CONTAINER_NAME}
    privileged: true
    user: root
    volumes:
      - ${CADDY_SSL_HOST_PATH}:/etc/caddy/ssl
      - ${LOG_PATH_HOST}/${CADDY_CONTAINER_NAME}:/var/log/caddy
      - ${DATA_PATH_HOST}/${CADDY_CONTAINER_NAME}:/root/.caddy
      - ${CADDY_CONFIG_PATH}:/etc/caddy
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    environment:
      TZ: "${TZ}"
    links:
      - ${METING_API_CONTAINER_NAME}
    networks:
      backend:
        ipv4_address: ${CADDY_BACKEND_IP}
