version: '3.8'

volumes:
  redis1:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}

x-build: &build
  build:
    context: ${REDIS_HOST_PATH}
    args:
      REDIS_VERSION: ${REDIS_VERSION}

services:
### REDIS NODE1 ##############################################
  redis1:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE1}
    hostname: ${REDIS_HOSTNAME_NODE1}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE1}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE1}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE1}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE1}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE1}
### REDIS NODE2 ##############################################
  redis2:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE2}
    hostname: ${REDIS_HOSTNAME_NODE2}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE2}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE2}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE2}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE2}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE2}

### REDIS NODE3 ##############################################
  redis3:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE3}
    hostname: ${REDIS_HOSTNAME_NODE3}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE3}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE3}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE3}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE3}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE3}

### REDIS NODE4 ##############################################
  redis4:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE4}
    hostname: ${REDIS_HOSTNAME_NODE4}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE4}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE4}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE4}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE4}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE4}

### REDIS NODE5 ##############################################
  redis5:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE5}
    hostname: ${REDIS_HOSTNAME_NODE5}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE5}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE5}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE5}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE5}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE5}

### REDIS NODE6 ##############################################
  redis6:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE6}
    hostname: ${REDIS_HOSTNAME_NODE6}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE6}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE6}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE6}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE6}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE6}

### REDIS NODE7 ##############################################
  redis7:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE7}
    hostname: ${REDIS_HOSTNAME_NODE7}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE7}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE7}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE7}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE7}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE7}

### REDIS NODE8 ##############################################
  redis8:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE8}
    hostname: ${REDIS_HOSTNAME_NODE8}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE8}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE8}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE8}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE8}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE8}

### REDIS NODE9 ##############################################
  redis9:
    <<: *build
    container_name: ${REDIS_CONTAINER_NAME_NODE9}
    hostname: ${REDIS_HOSTNAME_NODE9}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE9}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME_NODE9}:/var/log/redis
      - ${REDIS_CONF_HOST_PATH}/${REDIS_CONTAINER_NAME_NODE9}.conf:/redis-stack.conf
    ports:
      - "${REDIS_HOST_PORT_NODE9}:${REDIS_CONTAINER_PORT}"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP_NODE9}
