volumes:
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}

services:
### PHPMYADMIN ##############################################
  phpmyadmin:
    build:
      context: ${PMA_HOST_PATH}
      args:
        PMA_VERSION: ${PMA_VERSION}
    container_name: ${PMA_CONTAINER_NAME}
    hostname: ${PMA_HOSTNAME}
    ports:
      - "${PMA_HTTP_PORT}:80"
    environment:
      TZ: ${TZ}
      PMA_HOSTS: ${SQL_CONTAINER_NAME_NODE1},${SQL_CONTAINER_NAME_NODE2}
      PMA_PORTS: 3306
      PMA_USER: ${MYSQL_CLUSTER_USER}
      PMA_PASSWORD: ${MYSQL_CLUSTER_PASSWORD}
    networks:
      backend:
        ipv4_address: ${PMA_BACKEND_IP}
