version: '3.8'

networks:
  backend:
    external: true

services:
  kazoo-zookeeper:
    build:
      context: ../zookeeper
      args:
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    hostname: ${ZOOKEEPER_CONTAINER_NAME}
    ports:
      - "2181:2181"
    volumes:
      - ${ZOOKEEPER_PATH}/data:/data
      - ${ZOOKEEPER_PATH}/datalog:/datalog
    environment:
      - TZ=${TZ}
      - ZOO_MY_ID=${ZOOKEEPER_ID}
      - ZOO_SERVERS=${ZOOKEEPER_SERVERS}
    networks:
      backend:
        ipv4_address: ${KAZOO_ZOOKEEPER_IP}

  kazoo-kafka:
    build:
      context: ../kafka
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
    container_name: ${KAFKA_CONTAINER_NAME}
    hostname: ${KAFKA_CONTAINER_NAME}
    privileged: true
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - TZ=${TZ}
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093 # 9092内网访问,9093外网访问
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://${KAFKA_CONTAINER_NAME}:9092,EXTERNAL://${PUBLIC_IP}:9093 #公网ip
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ${KAFKA_PATH}/data:/bitnami/kafka
    depends_on:
      - ${ZOOKEEPER_CONTAINER_NAME}
    networks:
      backend:
        ipv4_address: ${KAZOO_KAFKA_IP}