volumes:
  etcd-ui:
    driver: ${VOLUMES_DRIVER}

services:

### ETCD UI ##############################################
  etcd-ui:
    build:
      context: ${ETCD_UI_HOST_PATH}
      args:
        ETCD_UI_VERSION: ${ETCD_UI_VERSION}
    container_name: ${ETCD_UI_CONTAINER_NAME}
    hostname: ${ETCD_UI_HOSTNAME}
    privileged: true
    user: root
    volumes:
      - "${CONF_HOST_PATH}/etcd-workbench.conf:/usr/tzfun/etcd-workbench/etcd-workbench.conf"
    environment:
      TZ: ${TZ}
    ports:
      - "${ETCD_UI_HOST_HTTP_PORT}:8002"
    networks:
      backend:
        ipv4_address: ${ETCD_UI_BACKEND_IP}