volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB ##############################################
  mongo:
    build:
      context: ${MONGO_HOST_PATH}
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    container_name: ${MONGO_CONTAINER_NAME}
    hostname: ${MONGO_HOSTNAME}
    privileged: true
    user: root
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/${MONGO_CONTAINER_NAME}/db:/data/db
      - ${DATA_PATH_HOST}/${MONGO_CONTAINER_NAME}/configdb:/data/configdb
    networks:
      backend:
        ipv4_address: ${MONGO_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "quit(db.runCommand(\"ping\").ok ? 0 : 2)"]
      interval: 10s
      timeout: 5s
      retries: 5