version: '3.8'

networks:
  backend:
    external: true

services:
  pulsar:
    build:
      context: ./pulsar
      args:
        PULSAR_VERSION: ${PULSAR_VERSION}
    hostname: ${PULSAR_CONTAINER_NAME}
    container_name: ${PULSAR_CONTAINER_NAME}
    volumes:
      - ${PULSAR_PATH}/data:/pulsar/data
#      - ${PULSAR_PATH}/conf:/pulsar/conf
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - TZ=${TZ}
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    networks:
      backend:
       ipv4_address: ${PULSAR_IP}

  pulsar-manager:
    build:
      context: ./pulsar-manager
    hostname: pulsar-manager
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - TZ=${TZ}
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    networks:
      backend:
        ipv4_address: ${PULSAR_MANAGER_IP}
    depends_on:
      - ${PULSAR_CONTAINER_NAME}

