volumes:
  mysql57:
    driver: ${VOLUMES_DRIVER}

services:

### Mysql57 ################################################
  mysql57:
    build:
      context: ${MYSQL57_HOST_PATH}
      args:
        - MYSQL_VERSION=${MYSQL57_VERSION}
    hostname: ${MYSQL57_HOSTNAME}
    container_name: ${MYSQL57_CONTAINER_NAME}
    privileged: true
    user: root
    volumes:
      - ${DATA_PATH_HOST}/${MYSQL57_CONTAINER_NAME}:/var/lib/mysql # 需要777权限
      - ${LOG_PATH_HOST}/${MYSQL57_CONTAINER_NAME}:/var/log
      - ${MYSQL57_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL57_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      MYSQL_DATABASE: "${MYSQL57_DATABASE}"
      MYSQL_USER: "${MYSQL57_USER}"
      MYSQL_PASSWORD: "${MYSQL57_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL57_ROOT_PASSWORD}"
    networks:
      backend:
        ipv4_address: ${MYSQL57_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10