
root@953:mc$ dc config
name: docker-env-mysql-cluster
services:
  mc-data1:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - ndbd
    container_name: mc-data1
    depends_on:
      mc-management:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-data1
    networks:
      backend:
        ipv4_address: 172.11.2.211
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-data1
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-data2:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - ndbd
    container_name: mc-data2
    depends_on:
      mc-management:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-data2
    networks:
      backend:
        ipv4_address: 172.11.2.212
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-data2
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-data3:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - ndbd
    container_name: mc-data3
    depends_on:
      mc-management:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-data3
    networks:
      backend:
        ipv4_address: 172.11.2.213
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-data3
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-data4:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - ndbd
    container_name: mc-data4
    depends_on:
      mc-management:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-data4
    networks:
      backend:
        ipv4_address: 172.11.2.214
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-data4
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-management:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - ndb_mgmd
    container_name: mc-management
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-management
    networks:
      backend:
        ipv4_address: 172.11.2.217
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-management
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-pma:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/phpmyadmin
      dockerfile: Dockerfile
      args:
        PMA_VERSION: latest
    container_name: mc-pma
    environment:
      PMA_HOSTS: mc-sql1,mc-sql2
      PMA_PASSWORD: "123456"
      PMA_PORTS: "3306"
      PMA_USER: mc
      TZ: Asia/Shanghai
    hostname: mc-pma
    networks:
      backend:
        ipv4_address: 172.11.2.210
    ports:
    - mode: ingress
      target: 80
      published: "8765"
      protocol: tcp
    privileged: true
    user: root
  mc-sql1:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - mysqld
    container_name: mc-sql1
    depends_on:
      mc-data1:
        condition: service_started
        required: true
      mc-data2:
        condition: service_started
        required: true
      mc-data3:
        condition: service_started
        required: true
      mc-data4:
        condition: service_started
        required: true
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-sql1
    networks:
      backend:
        ipv4_address: 172.11.2.215
    ports:
    - mode: ingress
      target: 3306
      published: "3310"
      protocol: tcp
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-sql1
      target: /var/lib/mysql
      bind:
        create_host_path: true
  mc-sql2:
    build:
      context: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_CLUSTER_VERSION: "8.4"
    command:
    - mysqld
    container_name: mc-sql2
    depends_on:
      mc-data1:
        condition: service_started
        required: true
      mc-data2:
        condition: service_started
        required: true
      mc-data3:
        condition: service_started
        required: true
      mc-data4:
        condition: service_started
        required: true
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai
    extra_hosts:
    - mc-data1:172.11.2.211
    - mc-data2:172.11.2.212
    - mc-data3:172.11.2.213
    - mc-data4:172.11.2.214
    - mc-management:172.11.2.217
    - mc-sql1:172.11.2.215
    - mc-sql2:172.11.2.216
    hostname: mc-sql2
    networks:
      backend:
        ipv4_address: 172.11.2.216
    ports:
    - mode: ingress
      target: 3306
      published: "3311"
      protocol: tcp
    privileged: true
    user: root
    volumes:
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/my.cnf
      target: /etc/my.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/jungle/github/zz-open/docker-env/cluster/mysql-cluster/mc/config/mysql-cluster.cnf
      target: /etc/mysql-cluster.cnf
      bind:
        create_host_path: true
    - type: bind
      source: /root/.docker-env/mysql-cluster/mc-sql2
      target: /var/lib/mysql
      bind:
        create_host_path: true
networks:
  backend:
    name: zz-backend
    external: true
x-extra_hosts:
- mc-management:172.11.2.217
- mc-data1:172.11.2.211
- mc-data2:172.11.2.212
- mc-data3:172.11.2.213
- mc-data4:172.11.2.214
- mc-sql1:172.11.2.215
- mc-sql2:172.11.2.216
root@953:mc$ 
