volumes:
  dtm:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}
  STORE_DRIVER: ${DTM_STORE_DRIVE}
  STORE_HOST: ${DTM_STORE_HOST}
  STORE_USER: ${DTM_STORE_USER}
  STORE_PASSWORD: ${DTM_STORE_PASSWORD}
  STORE_PORT: ${DTM_STORE_PORT}

x-build: &build
  build:
    context: ${DTM_HOST_PATH}
    args:
      - DTM_VERSION=${DTM_VERSION}

services:
### DTM ################################################
  dtm:
    <<: *build
    hostname: ${DTM_HOSTNAME}
    container_name: ${DTM_CONTAINER_NAME}
    privileged: true
    user: root
    environment:
      <<: *env
    ports:
      - "${DTM_HTTP_PORT}:36789"
      - "${DTM_GRPC_PORT}:36790"
    networks:
      backend:
        ipv4_address: ${DTM_BACKEND_IP}