version: "3.8"

networks:
  backend:
    external: true

services:
  node:
    build:
      context:  ./node
      args:
        NODE_VERSION: ${NODE_VERSION}
    hostname: node
    container_name: node
    volumes:
      - ./src:/usr/src/app
    environment:
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    networks:
      backend:
        ipv4_address: ${NODE_IP}
