volumes:
  soketi:
    driver: ${VOLUMES_DRIVER}

services:

### Soketi Server ########################################
  soketi:
    build:
      context: ${SOKETI_HOST_PATH}
      args:
        - SOKETI_VERSION=${SOKETI_VERSION}
    container_name: ${SOKETI_CONTAINER_NAME}
    hostname: ${SOKETI_HOSTNAME}
    privileged: true
    user: root
    volumes:
      - "${SOKETI_HOST_PATH}/config.json:/app/bin/config.json:ro"
    ports:
      - "${SOKETI_HOST_PORT}:6001"
      - "${SOKETI_METRICS_SERVER_PORT}:9601"
    networks:
      backend:
        ipv4_address: ${SOKETI_BACKEND_IP}