volumes:
  mysql8:
    driver: ${VOLUMES_DRIVER}

x-mysql8:
  extra-flags: &extra-flags "--default-time-zone=+8:00 --max-allowed-packet=100M --log-timestamps=system --innodb-use-native-aio=0"
  
services:

### Mysql ################################################
  mysql8:
    build:
      context: ${MYSQL8_HOST_PATH}
      args:
        - MYSQL_VERSION=${MYSQL8_VERSION}
    hostname: ${MYSQL8_HOSTNAME}
    container_name: ${MYSQL8_CONTAINER_NAME}
    volumes:
      - "${DATA_HOST_PATH}/${MYSQL8_CONTAINER_NAME}:/bitnami/mysql/data"
      - "${LOG_HOST_PATH}/${MYSQL8_CONTAINER_NAME}:/opt/bitnami/mysql/logs"
      - "${MYSQL57_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQL8_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL8_DATABASE}"
      MYSQL_USER: "${MYSQL8_USER}"
      MYSQL_PASSWORD: "${MYSQL8_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL8_ROOT_PASSWORD}"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
      MYSQL_CHARACTER_SET: "utf8mb4"
      MYSQL_COLLATE: "utf8mb4_general_ci"
      MYSQL_REPLICATION_MODE: "master"
      MYSQL_EXTRA_FLAGS: *extra-flags
      MYSQL_ENABLE_SLOW_QUERY: "1"
      MYSQL_LONG_QUERY_TIME: "1.0"
      MYSQL_SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    networks:
      backend:
        ipv4_address: ${MYSQL8_BACKEND_IP}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
