volumes:
  mysql57:
    driver: ${VOLUMES_DRIVER}

x-mysql57:
  extra-flags: &extra-flags "--default-time-zone=+8:00 --max-allowed-packet=100M --log-timestamps=system"
  
services:

### Mysql57 ################################################
  mysql57:
    build:
      context: ${MYSQL57_HOST_PATH}
    hostname: ${MYSQL57_HOSTNAME}
    container_name: ${MYSQL57_CONTAINER_NAME}
    volumes:
      - "${DATA_HOST_PATH}/${MYSQL57_CONTAINER_NAME}:/bitnami/mysql/data"
      - "${LOG_HOST_PATH}/${MYSQL57_CONTAINER_NAME}:/opt/bitnami/mysql/logs"
      - "${MYSQL57_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQL57_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL57_DATABASE}"
      MYSQL_USER: "${MYSQL57_USER}"
      MYSQL_PASSWORD: "${MYSQL57_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL57_ROOT_PASSWORD}"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
      MYSQL_CHARACTER_SET: "utf8mb4"
      MYSQL_COLLATE: "utf8mb4_general_ci"
      MYSQL_REPLICATION_MODE: "master"
      MYSQL_EXTRA_FLAGS: *extra-flags
      MYSQL_ENABLE_SLOW_QUERY: "1"
      MYSQL_LONG_QUERY_TIME: "1.0"
    networks:
      backend:
        ipv4_address: ${MYSQL57_BACKEND_IP}
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
