volumes:
  mysql57:
    driver: ${VOLUMES_DRIVER}

services:

### Mysql57 ################################################
  mysql57:
    build:
      context: ${MYSQL57_HOST_PATH}
    hostname: ${MYSQL57_HOSTNAME}
    container_name: ${MYSQL57_CONTAINER_NAME}
    volumes:
      - ${DATA_HOST_PATH}/${MYSQL57_CONTAINER_NAME}:/bitnami/mysql/data
      - ${LOG_HOST_PATH}/${MYSQL57_CONTAINER_NAME}:/bitnami/mysql/logs
      - ${MYSQL57_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL57_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL57_DATABASE}"
      MYSQL_USER: "${MYSQL57_USER}"
      MYSQL_PASSWORD: "${MYSQL57_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL57_ROOT_PASSWORD}"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    networks:
      backend:
        ipv4_address: ${MYSQL57_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
