volumes:
  portainer:
    driver: ${VOLUMES_DRIVER}

secrets:
  portainer_admin_password:
    file: ${PORTAINER_HOST_PATH}/portainer_admin_password

services:

### Portainer ############################################
  portainer:
    build:
      context: ${PORTAINER_HOST_PATH}
      args:
        - PORTAINER_VERSION=${PORTAINER_VERSION}
    command: ['--admin-password-file', '/run/secrets/portainer_admin_password']
    container_name: ${PORTAINER_CONTAINER_NAME}
    hostname: ${PORTAINER_HOSTNAME}
    volumes:
      - ${DOCKER_SOCK_PATH_HOST}:/var/run/docker.sock:ro
      - ${DATA_HOST_PATH}/${PORTAINER_CONTAINER_NAME}:/data
    ports:
      - "${PORTAINER_HTTP_HOST_PORT}:9000"
      - "${PORTAINER_HTTPS_HOST_PORT}:9443"
    networks:
      backend:
        ipv4_address: ${PORTAINER_BACKEND_IP}
    secrets:
        - portainer_admin_password
