volumes:
  xxjob:
    driver: ${VOLUMES_DRIVER}

x-variable:
  PARAMS: &PARAMS '--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai'


services:

### xx-job ########################################
  xxjob:
    build:
      context: ${XXJOB_HOST_PATH}
      args:
        - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
    container_name: ${XXJOB_CONTAINER_NAME}
    hostname: ${XXJOB_HOSTNAME}
    privileged: true
    user: root
    volumes:
      - "${DATA_PATH_HOST}/${ETCD_CONTAINER_NAME}:/tmp:/data/applogs"
    ports:
      - "${XXJOB_HOST_HTTP_PORT}:8080"
    environment:
       - *PARAMS
    networks:
      backend:
        ipv4_address: ${XXJOB_BACKEND_IP}
