version: '3.8'

volumes:
  portainer:
    driver: ${VOLUMES_DRIVER}

services:

### Portainer ############################################
  portainer:
    build:
      context: ${PORTAINER_HOST_PATH}
      args:
        - PORTAINER_VERSION=${PORTAINER_VERSION}
    container_name: ${PORTAINER_CONTAINER_NAME}
    hostname: ${PORTAINER_HOSTNAME}
    privileged: true
    volumes:
      - ${DOCKER_SOCK_PATH_HOST}:/var/run/docker.sock
      - ${DATA_PATH_HOST}/${PORTAINER_CONTAINER_NAME}:/data
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${PORTAINER_HOST_PORT}:9000"
    networks:
      backend:
        ipv4_address: ${PORTAINER_BACKEND_IP}