volumes:
  zookeeper:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}
  ZOO_SERVERS: ${ZOOKEEPER_SERVERS}
  ZOO_4LW_COMMANDS_WHITELIST: \* #stat,conf,envi

x-build: &build
  build:
    context: ${ZOOKEEPER_HOST_PATH}
    args:
      ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}

services:
### ZOOKEEPER ##############################################
  zookeeper:
    <<: *build
    container_name: ${ZOOKEEPER_NAME}
    hostname: ${ZOOKEEPER_NAME}
    privileged: true
    user: root
    ports:
      - "${ZOOKEEPER_HOST_PORT}:2181"
    environment:
      <<: *env
      ZOO_MY_ID: ${ZOOKEEPER_ID}
    volumes:
      - ${DATA_PATH_HOST}/${ZOOKEEPER_CONTAINER_NAME}:/data
      - ${LOG_PATH_HOST}/${ZOOKEEPER_CONTAINER_NAME}:/datalog
    networks:
      backend:
        ipv4_address: ${ZOOKEEPER_BACKEND_IP}