volumes:
  nginx:
    driver: ${VOLUMES_DRIVER}
    
services:
### NGINX ##############################################
  nginx:
    build:
      context: ${NGINX_HOST_PATH}
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER_NAME}
    hostname: ${NGINX_HOSTNAME}
    volumes:
      - "${NGINX_WWW_HOST_PATH}:/app"
      - "${LOG_HOST_PATH}/${NGINX_CONTAINER_NAME}:/bitnami/nginx/logs"
      - "${NGINX_HOST_PATH}/sites:/opt/bitnami/nginx/conf/server_blocks/:ro"
      - "${NGINX_HOST_PATH}/ssl:/certs"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    environment:
      TZ: ${TZ}
    networks:
      backend:
        ipv4_address: ${NGINX_BACKEND_IP}

