volumes:
  nginx:
    driver: ${VOLUMES_DRIVER}

x-build: &build
  build:
    context: ${NGINX_HOST_PATH}
    args:
      - NGINX_VERSION=${NGINX_VERSION}
      - http_proxy
      - https_proxy
      - no_proxy
    
services:
### NGINX ##############################################
  nginx:
    <<: *build
    container_name: ${NGINX_CONTAINER_NAME}
    hostname: ${NGINX_HOSTNAME}
    volumes:
      - "./www/:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}"
      - "${NGINX_HOST_PATH}/sites:/etc/nginx/sites-available"
      - "${NGINX_HOST_PATH}/ssl:/etc/nginx/ssl"
      - "${HOST_LOG_PATH}/${NGINX_CONTAINER_NAME}:/var/log/nginx"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    environment:
      TZ: ${TZ}
    networks:
      backend:
        ipv4_address: ${NGINX_BACKEND_IP}

