volumes:
  nginx:
    driver: ${VOLUMES_DRIVER}
    
services:
### NGINX ##############################################
  nginx:
    build:
      context: ${NGINX_HOST_PATH}
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER_NAME}
    hostname: ${NGINX_HOSTNAME}
    volumes:
      - "${LOG_HOST_PATH}/${NGINX_CONTAINER_NAME}:/var/log/nginx"
      - "${NGINX_WWW_HOST_PATH}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}"
      # - "${NGINX_HOST_PATH}/sites:/etc/nginx/sites-available"
      # - "${NGINX_HOST_PATH}/ssl:/etc/nginx/ssl"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    environment:
      TZ: ${TZ}
    networks:
      backend:
        ipv4_address: ${NGINX_BACKEND_IP}

