version: '3.8'

volumes:
  mc-sql1:
    driver: ${VOLUMES_DRIVER}
  mc-sql2:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}
  MYSQL_ROOT_PASSWORD: ${MYSQL_CLUSTER_ROOT_PASSWORD}
  SERVICE_NAME: ${MYSQL_CLUSTER_SERVICE_NAME}

x-build: &build
  build:
    context: ${MYSQL_CLUSTER_HOST_PATH}
    args:
      MYSQL_CLUSTER_VERSION: ${MYSQL_CLUSTER_VERSION}

x-command1: &command1 "mysqld --ndb-nodeid=6 --ndb-connectstring ${MYSQL_CLUSTER_MANAGEMENT_CONTAINER_NAME} --default-storage-engine=NDBCLUSTER"
x-command2: &command2 "mysqld --ndb-nodeid=7 --ndb-connectstring ${MYSQL_CLUSTER_MANAGEMENT_CONTAINER_NAME} --default-storage-engine=NDBCLUSTER"

services:
### MYSQL CLUSTER SQL NODE1 ##############################################
  mc-sql1:
    <<: *build
    container_name: ${MYSQL_CLUSTER_SQL_CONTAINER_NAME_NODE1}
    hostname: ${MYSQL_CLUSTER_SQL_HOSTNAME_NODE1}
    command: *command1
    user: root
    privileged: true
    volumes:
      - "${DATA_PATH_HOST}/${MYSQL_CLUSTER_SQL_CONTAINER_NAME_NODE1}/:/var/lib/mysql/"
      - "${MYSQL_CLUSTER_CNF_HOST_PATH}:/etc/mysql-cluster.cnf"
      - "${MYSQL_CLUSTER_SQL_ENTRYPOINT_INITDB_NODE1}:/docker-entrypoint-initdb.d/"
    ports:
      - "${MYSQL_CLUSTER_SQL_HOST_PORT_NODE1}:3306"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${MYSQL_CLUSTER_SQL_BACKEND_IP_NODE1}

### MYSQL CLUSTER SQL NODE2 ##############################################
  mc-sql2:
    <<: *build
    container_name: ${MYSQL_CLUSTER_SQL_CONTAINER_NAME_NODE2}
    hostname: ${MYSQL_CLUSTER_SQL_HOSTNAME_NODE2}
    command: *command2
    user: root
    privileged: true
    volumes:
      - "${DATA_PATH_HOST}/${MYSQL_CLUSTER_SQL_CONTAINER_NAME_NODE2}/:/var/lib/mysql/"
      - "${MYSQL_CLUSTER_CNF_HOST_PATH}:/etc/mysql-cluster.cnf"
      - "${MYSQL_CLUSTER_SQL_ENTRYPOINT_INITDB_NODE2}:/docker-entrypoint-initdb.d/"
    ports:
      - "${MYSQL_CLUSTER_SQL_HOST_PORT_NODE2}:3306"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${MYSQL_CLUSTER_SQL_BACKEND_IP_NODE2}