version: '3.8'

volumes:
  redis-devops:
    driver: ${VOLUMES_DRIVER}

services:

### Redis ##############################################
  redis-devops:
    build:
      context: ${REDIS_HOST_PATH}
      args:
        - REDIS_STACK_VERSION=${REDIS_STACK_VERSION}
    hostname: ${REDIS_HOSTNAME}
    container_name: ${REDIS_CONTAINER_NAME}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/${REDIS_CONTAINER_NAME}:/data
      - ${LOG_PATH_HOST}/${REDIS_CONTAINER_NAME}:/var/log/redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    environment:
      - "TZ=${TZ}"
      - "REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --appendonly yes"
    networks:
      frontend:
        ipv4_address: ${REDIS_FRONTEND_IP}
      backend:
        ipv4_address: ${REDIS_BACKEND_IP}