version: '3.8'

volumes:
  app:
    driver: ${VOLUMES_DRIVER}

services:

### Go Application ################################################
  app:
    build:
      context: ${APPLICATION_HOST_PATH}
      args:
        - APPLICATION_VERSION=${APPLICATION_VERSION}
    container_name: ${APPLICATION_CONTAINER_NAME}
    hostname: ${APPLICATION_HOSTNAME}
    privileged: true
    environment:
      - TZ=${TZ}
    ports:
      - "${APPLICATION_HOST_HTTP_PORT}:12000"
    networks:
      backend:
        ipv4_address: ${APPLICATION_BACKEND_IP}
