version: '3.8'

volumes:
  gitlab-runner:
    driver: ${VOLUMES_DRIVER}

services:

### Gitlab Runner ########################################
  gitlab-runner:
      build:
        context: ${GITLAB_RUNNER_HOST_PATH}
        args:
          - GITLAB_RUNNER_VERSION=${GITLAB_RUNNER_VERSION}
      container_name: ${GITLAB_RUNNER_CONTAINER_NAME}
      hostname: ${GITLAB_RUNNER_HOSTNAME}
      environment:
        - CI_SERVER_URL=${GITLAB_CI_SERVER_URL}
        - REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
        - RUNNER_NAME=${COMPOSE_PROJECT_NAME}-runner
        - REGISTER_NON_INTERACTIVE=${GITLAB_REGISTER_NON_INTERACTIVE}
        - RUNNER_EXECUTOR=shell
      volumes:
        - ${DATA_PATH_HOST}/gitlab-runner/runner:/etc/gitlab-runner
        - ${DOCKER_SOCK_PATH_HOST}:/var/run/docker.sock:rw
      networks:
        backend:
          ipv4_address: ${GITLAB_RUNNER_BACKEND_IP}