version: '3.8'

volumes:
  mongo-webui:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB WEBUI ##############################################
  mongo-webui:
    build:
      context: ${MONGO_WEBUI_HOST_PATH}
      args:
        - MONGO_WEBUI_VERSION=${MONGO_WEBUI_VERSION}
    container_name: ${MONGO_WEBUI_CONTAINER_NAME}
    hostname: ${MONGO_WEBUI_HOSTNAME}
    privileged: true
    user: root
    networks:
      backend:
        ipv4_address: ${MONGO_WEBUI_BACKEND_IP}