config.reload.automatic: true
http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts:
- http://es:9200
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
