volumes:
  kafka-ui:
    driver: ${VOLUMES_DRIVER}

services:
### KAFKA UI ##############################################
  kafka-ui:
    build:
      context: ${KAFKA_UI_HOST_PATH}
      args:
        - KAFKA_UI_VERSION=${KAFKA_UI_VERSION}
    container_name: ${KAFKA_UI_CONTAINER_NAME}
    hostname: ${KAFKA_UI_HOSTNAME}
    ports:
      - "${KAFKA_UI_HOST_HTTP_PORT}:9000"
    environment:
      TZ: ${TZ}
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERS}
    networks:
      backend:
        ipv4_address: ${KAFKA_UI_BACKEND_IP}
    depends_on:
      - "${KAFKA_CONTAINER_NAME}"
