volumes:
  caddy:
    driver: ${VOLUMES_DRIVER}

services:

### Caddy Server #########################################
  caddy:
    build:
      context: ${CADDY_HOST_PATH}
      args:
        - CADDY_VERSION=${CADDY_VERSION}
    hostname: ${CADDY_HOSTNAME}
    container_name: ${CADDY_CONTAINER_NAME}
    volumes:
      - "${CADDY_HOST_PATH}/config:/config"
      - "${DATA_PATH_HOST}/caddy:/data"
      - "${CADDY_HOST_PATH}/Caddyfile:/etc/caddy/Caddyfile"
      - "${CADDY_HOST_PATH}/www:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}"
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    environment:
      TZ: ${TZ}
    networks:
      backend:
        ipv4_address: ${CADDY_BACKEND_IP}