volumes:
  tomcat8:
    driver: ${VOLUMES_DRIVER}

services:

### Tomcat ###############################################
  tomcat8:
    build:
      context: ${TOMCAT8_HOST_PATH}
      args:
        - TOMCAT_VERSION=${TOMCAT8_VERSION}
    container_name: ${TOMCAT8_CONTAINER_NAME}
    hostname: ${TOMCAT8_HOSTNAME}
    privileged: true
    user: root
    volumes:
      - ${LOG_PATH_HOST}/${TOMCAT8_CONTAINER_NAME}:/usr/local/tomcat/logs
      - ${TOMCAT8_HOST_PATH}/webapps:/usr/local/tomcat/webapps
      - ${TOMCAT8_HOST_PATH}/conf:/usr/local/tomcat/conf
    environment:
      TZ: ${TZ}
    ports:
      - "${TOMCAT8_HOST_HTTP_PORT}:8080"
    networks:
      backend:
        ipv4_address: ${TOMCAT8_BACKEND_IP}