services:
  apache:
    ports:
      - "8211:8211"
      - "8212:8212"
      - "8213:8213"
      - "8221:8221"
      - "8222:8222"
      - "8223:8223"
      - "8224:8224"
      - "8231:8231"
      - "8242:8242"
    extra_hosts:
      - "legion.admin.zz:172.11.3.91"
      - "legion.agent.zz:172.11.3.91"
      - "legion.api.zz:172.11.3.91"
      - "legion.client.zz:172.11.3.91"
      - "newenglish.store.zz:172.11.3.91"
      - "newenglish.admin.zz:172.11.3.91"
      - "newenglish.client.zz:172.11.3.91"
      - "newenglish.web.zz:172.11.3.91"
      - "yaf.a.com:172.11.3.91"
      - "yaf.a.cn:172.11.3.91"
  php-fpm:
    extra_hosts:
      - "legion.api.zz:172.11.3.91"