volumes:
  ndb-sql1:
    driver: ${VOLUMES_DRIVER}
  ndb-sql2:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}
  MYSQL_ROOT_PASSWORD: ${MYSQL_CLUSTER_ROOT_PASSWORD}
  MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}

x-build: &build
  build:
    context: ${MYSQL_CLUSTER_HOST_PATH}
    args:
      MYSQL_CLUSTER_VERSION: ${MYSQL_CLUSTER_VERSION}

x-command: &command "mysqld"

services:
### MYSQL CLUSTER SQL NODE1 ##############################################
  ndb-sql1:
    <<: *build
    container_name: ${SQL_CONTAINER_NAME_NODE1}
    hostname: ${SQL_HOSTNAME_NODE1}
    command: *command
    volumes:
      - "${DATA_HOST_PATH}/${SQL_CONTAINER_NAME_NODE1}/:/var/lib/mysql/"
      - "${MYSQL_CLUSTER_HOST_PATH}/config/my.cnf:/etc/my.cnf"
      - "${MYSQL_CLUSTER_HOST_PATH}/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf"
      - "${MYSQL_CLUSTER_SQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d/"
    ports:
      - "${SQL_HOST_PORT_NODE1}:3306"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${SQL_BACKEND_IP_NODE1}
    depends_on:
      - ${DATA_CONTAINER_NAME_NODE1}
      - ${DATA_CONTAINER_NAME_NODE2}
      - ${DATA_CONTAINER_NAME_NODE3}
      - ${DATA_CONTAINER_NAME_NODE4}

### MYSQL CLUSTER SQL NODE2 ##############################################
  ndb-sql2:
    <<: *build
    container_name: ${SQL_CONTAINER_NAME_NODE2}
    hostname: ${SQL_HOSTNAME_NODE2}
    command: *command
    volumes:
      - "${DATA_HOST_PATH}/${SQL_CONTAINER_NAME_NODE2}/:/var/lib/mysql/"
      - "${MYSQL_CLUSTER_HOST_PATH}/config/my.cnf:/etc/my.cnf"
      - "${MYSQL_CLUSTER_HOST_PATH}/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf"
      - "${MYSQL_CLUSTER_SQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d/"
    ports:
      - "${SQL_HOST_PORT_NODE2}:3306"
    environment:
      <<: *env
    networks:
      backend:
        ipv4_address: ${SQL_BACKEND_IP_NODE2}
    depends_on:
      - ${DATA_CONTAINER_NAME_NODE1}
      - ${DATA_CONTAINER_NAME_NODE2}
      - ${DATA_CONTAINER_NAME_NODE3}
      - ${DATA_CONTAINER_NAME_NODE4}
