version: '3.8'

networks:
  backend:
    external: true

services:
  openresty:
    build:
      context: ./openresty
    hostname: openresty
    container_name: openresty
    volumes:
      - ./www:/var/www:cached
      - ${OPENRESTY_HOST_LOG_PATH}:/usr/local/openresty/nginx/logs
      - ${OPENRESTY_SITES_PATH}:/etc/nginx/sites-available
      - ${OPENRESTY_SSL_PATH}:/etc/nginx/ssl
      - ${OPENRESTY_LUA_PATH}:/usr/local/openresty/nginx/lua/
    environment:
      - TZ=${TZ}
    ports:
      - "${OPENRESTY_HOST_HTTP_PORT}:80"
      - "${OPENRESTY_HOST_HTTPS_PORT}:443"
    networks:
      backend:
        ipv4_address: ${OPENRESTY_IP}